version: '3'
services:
    rocketchat:
        image: rocketchat/rocket.chat:3.0.4
        container_name: rocketchat
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo1:27017/rocketchat
            - MONGO_OPLOG_URL=mongodb://mongo1:27017/local
        ports:
            - "3000:3000"
        depends_on: 
            - mongo-instance-1
            - mongo-instance-2
            - mongo-instance-3

    mongo-instance-1:
        image: mongo:4
        container_name: mongo1
        restart: unless-stopped
        command: mongod --oplogSize 128 --replSet rs0
        ports:
            - "27017:27017"

    mongo-instance-2:
        image: mongo:4
        container_name: mongo2
        restart: unless-stopped
        command: mongod --replSet rs0
        ports:
            - "27018:27017"
        depends_on: 
            - mongo-instance-1
            
    mongo-instance-3:
        image: mongo:4
        container_name: mongo3
        restart: unless-stopped
        command: mongod --replSet rs0
        ports:
            - "27019:27017"
        depends_on: 
            - mongo-instance-2

networks:
    default:
        external:
            name: your-network